/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Custom
{
    public class CustomPointCloud : Message
    {
        public const string RosMessageName = "custom_point_cloud_msg/CustomPointCloud";

        //  This represents a Point with reference coordinate frame and timestamp
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }

        public CustomPointCloud()
        {
        }

        public CustomPointCloud(float x, float y, float z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }
}
