/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Custom
{
    public class CustomPointCloudMsg : Message
    {
        public const string RosMessageName = "custom_point_cloud_msg/CustomPointCloudMsg";

        //  This represents a Point with reference coordinate frame and timestamp
        public Header header { get; set; }
        public CustomPointCloud[] dataPoints { get; set; }


        public CustomPointCloudMsg()
        {
            this.header = new Header();
            this.dataPoints = new CustomPointCloud[0];
        }

        public CustomPointCloudMsg(Header header, CustomPointCloud[] points)
        {
            this.header = header;
            this.dataPoints = points;
        }
    }
}
